In [23]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.2+cu121


## Intro to Tensors

### Creating Tensors

PyTorch Tensors are created using 'torch.tensor()'

In [24]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [25]:
scalar.ndim

0

In [26]:
# Get tensor back as Python int
scalar.item()

7

In [27]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [28]:
vector.ndim

1

In [29]:
vector.shape

torch.Size([2])

In [30]:
# Matrix
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [31]:
MATRIX.ndim

2

In [32]:
MATRIX[1]

tensor([3, 4])

In [33]:
MATRIX.shape

torch.Size([2, 2])

In [34]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], [2, 3, 4], [5, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [5, 6, 7]]])

In [35]:
TENSOR.ndim

3

In [36]:
TENSOR.shape

torch.Size([1, 3, 3])

In [38]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]])

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [49]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3649, 0.6177, 0.5468, 0.9323],
        [0.4467, 0.3037, 0.0700, 0.4154],
        [0.0217, 0.8361, 0.6509, 0.4151]])

In [50]:
random_tensor.ndim

2

In [51]:
random_tensor.shape

torch.Size([3, 4])

In [52]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [53]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
ones.dtype

torch.float32

In [58]:
random_tensor.dtype

torch.float32

### Creating a Range of tensors and tensors-like

In [65]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is on of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device

In [72]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [73]:
float_32_tensor.dtype

torch.float32

In [74]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [76]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [77]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [78]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting tensor attributes

1. Tensors not the right datatype - to get datatype from a tensor, use 'tensor.dtype'
2. Tensors not the right shape - to get shape from a tensor, use 'tensor.shap'
3. Tensors not on the right device - to get device from a tensor, use 'tensor.device'

In [79]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3713, 0.5312, 0.0253, 0.8910],
        [0.6349, 0.0915, 0.2095, 0.5315],
        [0.3804, 0.9911, 0.6547, 0.3425]])

In [80]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Size of tensor: {some_tensor.size()}") # Same as the shape, just another way it may show up
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3713, 0.5312, 0.0253, 0.8910],
        [0.6349, 0.0915, 0.2095, 0.5315],
        [0.3804, 0.9911, 0.6547, 0.3425]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Tensor operations

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [85]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [86]:
# Subtraction
tensor = tensor - 10
tensor

tensor([1, 2, 3])

In [87]:
# Multiplication
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [88]:
# Division
tensor = tensor / 10
tensor

tensor([1., 2., 3.])

In [92]:
# Built-ins
tensor = tensor.mul(10)
tensor

tensor([1.0000e+11, 1.0240e+14, 5.9049e+15])

In [93]:
tensor = tensor.div(10)
tensor

tensor([1.0000e+10, 1.0240e+13, 5.9049e+14])

In [94]:
tensor = tensor.pow(10)
tensor

tensor([inf, inf, inf])

In [98]:
tensor = torch.tensor([1, 2, 3])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
* `(2, 3) @ (3, 2)` -> (2, 2)
* `(3, 2) @ (2, 3)` -> (3, 3)

In [116]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [117]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [118]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [119]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.08 ms, sys: 271 µs, total: 1.35 ms
Wall time: 934 µs


In [120]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 170 µs, sys: 43 µs, total: 213 µs
Wall time: 238 µs


tensor(14)

In [121]:
matrix1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
matrix2 = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])
matrix1, matrix2

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [122]:
torch.matmul(matrix1, matrix2)

tensor([[ 58,  64],
        [139, 154]])

In [123]:
# `(3, 2) @ (3, 2)` won't work
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [124]:
# `(2, 3) @ (3, 2)` will work
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.3793, 0.9055],
        [0.4718, 0.6431]])

In [125]:
# `(3, 2) @ (2, 3)` will work
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.2389, 0.5233, 0.1153],
        [0.7205, 1.3878, 0.3215],
        [0.4826, 0.9988, 0.2249]])

### One of the most common errors in deep learning: shape errors