In [142]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.2+cu121


## Intro to Tensors

### Creating Tensors

PyTorch Tensors are created using 'torch.tensor()'

In [143]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [144]:
scalar.ndim

0

In [145]:
# Get tensor back as Python int
scalar.item()

7

In [146]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [147]:
vector.ndim

1

In [148]:
vector.shape

torch.Size([2])

In [149]:
# Matrix
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [150]:
MATRIX.ndim

2

In [151]:
MATRIX[1]

tensor([3, 4])

In [152]:
MATRIX.shape

torch.Size([2, 2])

In [153]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], [2, 3, 4], [5, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [5, 6, 7]]])

In [154]:
TENSOR.ndim

3

In [155]:
TENSOR.shape

torch.Size([1, 3, 3])

In [156]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]])

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [157]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8964, 0.4556, 0.6323, 0.3489],
        [0.4017, 0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000, 0.1610]])

In [158]:
random_tensor.ndim

2

In [159]:
random_tensor.shape

torch.Size([3, 4])

In [160]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [161]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [162]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [163]:
ones.dtype

torch.float32

In [164]:
random_tensor.dtype

torch.float32

### Creating a Range of tensors and tensors-like

In [165]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [166]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is on of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not on the right device

In [167]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [168]:
float_32_tensor.dtype

torch.float32

In [169]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [170]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [171]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [172]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting tensor attributes

1. Tensors not the right datatype - to get datatype from a tensor, use 'tensor.dtype'
2. Tensors not the right shape - to get shape from a tensor, use 'tensor.shap'
3. Tensors not on the right device - to get device from a tensor, use 'tensor.device'

In [173]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7843, 0.6775, 0.7653, 0.8990],
        [0.5795, 0.3956, 0.7390, 0.3317],
        [0.5313, 0.1853, 0.5148, 0.1994]])

In [174]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Size of tensor: {some_tensor.size()}") # Same as the shape, just another way it may show up
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7843, 0.6775, 0.7653, 0.8990],
        [0.5795, 0.3956, 0.7390, 0.3317],
        [0.5313, 0.1853, 0.5148, 0.1994]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Tensor operations

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [175]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [176]:
# Subtraction
tensor = tensor - 10
tensor

tensor([1, 2, 3])

In [177]:
# Multiplication
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [178]:
# Division
tensor = tensor / 10
tensor

tensor([1., 2., 3.])

In [179]:
# Built-ins
tensor = tensor.mul(10)
tensor

tensor([10., 20., 30.])

In [180]:
tensor = tensor.div(10)
tensor

tensor([1., 2., 3.])

In [181]:
tensor = tensor.pow(10)
tensor

tensor([1.0000e+00, 1.0240e+03, 5.9049e+04])

In [182]:
tensor = torch.tensor([1, 2, 3])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
* `(2, 3) @ (3, 2)` -> (2, 2)
* `(3, 2) @ (2, 3)` -> (3, 3)

In [183]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [184]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [185]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [186]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.01 ms, sys: 387 µs, total: 1.4 ms
Wall time: 1.01 ms


In [187]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 178 µs, sys: 68 µs, total: 246 µs
Wall time: 310 µs


tensor(14)

In [188]:
matrix1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
matrix2 = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])
matrix1, matrix2

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [189]:
torch.matmul(matrix1, matrix2)

tensor([[ 58,  64],
        [139, 154]])

In [190]:
# `(3, 2) @ (3, 2)` won't work
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [191]:
# `(2, 3) @ (3, 2)` will work
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.4814, 0.6487],
        [1.0961, 1.4713]])

In [192]:
# `(3, 2) @ (2, 3)` will work
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[1.1554, 0.9219, 1.2137],
        [0.9446, 0.6545, 0.8077],
        [0.3839, 0.2806, 0.3554]])

### One of the most common errors in deep learning: shape errors

In [193]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)  # torch.mm is an alias for matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix tensor shape issues, manipulate the shape of one of the tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [194]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [195]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [196]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes:  tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes:  tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [197]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [198]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [199]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [200]:
# Find the mean - note: torch.mean() function requires a tensor of float32 or another complex number to work
torch.mean(x, dtype=torch.float32), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [201]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [202]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [203]:
# Find the position in tensor that has min value with argmin -> returns index position
x.argmin()

tensor(0)

In [204]:
x[0]

tensor(0)

In [205]:
# Find the position in tensor that has max value with argmax -> returns index position
x.argmax()

tensor(9)

In [206]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqeeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [207]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [208]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [209]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [210]:
# Changing z changes x because a view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [211]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [212]:
# VStack
x_vstacked = torch.vstack([x, x, x, x])
x_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [213]:
# HStack
x_hstacked = torch.hstack([x, x, x, x])
x_hstacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [214]:
# Squeeze - torch.squeeze() removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [215]:
# Unsqueeze - torch.unsqueeze() adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add extra dimension to x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [216]:
# Permute - torch.permute() rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis or dimension order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing - selecting data from tensors

Indexing with PyTorch is similar to indexing with NumPy

In [217]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [218]:
# Index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [219]:
# Index on middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [220]:
# Index on inner bracket (last dimension)
x[0][0][0], x[0, 0, 0]

(tensor(1), tensor(1))

In [221]:
# Can use ':' to select 'all' of the target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [222]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [223]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [224]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [225]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [226]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

PyTorch has functionality to interact with it.

* Data in NumPy -> PyTorch tensor: `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy: `torch.Tensor.numpy()`

In [227]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from NumPy -> PyTorch, PyTorch reflects NumPy's float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [228]:
# What will changing the value of the array do to the tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [229]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # warning: reflects original tensor dtype to the new NumPy values
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [230]:
# What will changing the tensor do to the NumPy array? - No change, they do not share memory
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility - Trying to take the random out of random

How a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

A seed "flavors" the randomness.

In [231]:
random_tensorA = torch.rand(3, 4)
random_tensorB = torch.rand(3, 4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA == random_tensorB)

tensor([[0.3878, 0.9579, 0.8932, 0.5257],
        [0.0724, 0.1792, 0.6991, 0.8631],
        [0.6793, 0.7896, 0.5807, 0.5846]])
tensor([[0.8938, 0.7874, 0.5334, 0.5065],
        [0.3767, 0.6547, 0.8055, 0.2323],
        [0.7001, 0.8818, 0.8782, 0.5274]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [232]:
# Add seeds to make them predictable and therefore reproducable
# Set the random seed
RANDOM_SEED = 123
torch.manual_seed(RANDOM_SEED)
random_tensorC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensorD = torch.rand(3, 4)

print(random_tensorC)
print(random_tensorD)
print(random_tensorC == random_tensorD)

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])
tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes

### 1. Getting a GPU

* Easiest - Use Google Colab for a free GPU
* Use your own GPU - takes a bit of setup and requires purchasing a GPU
* Use cloud computing - GCP, AWS, Azure: allow you to rent computers on the cloud

In [233]:
!nvidia-smi

/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Fri Dec 22 19:34:26 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.01              Driver Version: 536.67       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 970         On  | 00000000:01:00.0  On |                  N/A |
|  0%   46C    P8              24W / 200W |   1126MiB /  4096MiB |     13%      Default |
|                                         |                      |                  

### 2. Check for GPU access with PyTorch

In [234]:
torch.cuda.is_available()

True

Best practices call for setting up device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [235]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [236]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

In [237]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [238]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [239]:
# If tensor is on GPU, can't transform to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [240]:
# To fix GPU tensor with NumPy issue, first set it to cpu
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [241]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Exercises

In [242]:
# Create a random tensor with shape (7, 7)
tensorA = torch.rand(7, 7)
tensorA

tensor([[0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274, 0.3821],
        [0.6605, 0.8536, 0.5932, 0.6367, 0.9826, 0.2745, 0.6584],
        [0.2775, 0.8573, 0.8993, 0.0390, 0.9268, 0.7388, 0.7179],
        [0.7058, 0.9156, 0.4340, 0.0772, 0.3565, 0.1479, 0.5331],
        [0.4066, 0.2318, 0.4545, 0.9737, 0.4606, 0.5159, 0.4220],
        [0.5786, 0.9455, 0.8057, 0.6775, 0.6087, 0.6179, 0.6932],
        [0.4354, 0.0353, 0.1908, 0.9268, 0.5299, 0.0950, 0.5789]])

In [243]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
tensorB = torch.rand(1, 7)
tensorB

tensor([[0.9131, 0.0275, 0.1634, 0.3009, 0.5201, 0.3834, 0.4451]])

In [244]:
tensor_result = torch.mm(tensorA, tensorB.T)
tensor_result

tensor([[0.7960],
        [1.8244],
        [1.5204],
        [1.2432],
        [1.3700],
        [1.7518],
        [1.2782]])

In [245]:
# Set the random seed to 0 and perform the same operations
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensorA = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
tensorB = torch.rand(1, 7)

tensor_result = torch.mm(tensorA, tensorB.T)
tensor_result

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])